type: daliaIT.co3.package.Package
properties:
  name:         co3
  author:       Oliver Anan <oliver@ananit.de>
  license:      "http://www.gnu.org/licenses/lgpl-3.0-standalone.html"
  src           src
  resource:     resource